<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BookSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('books')->upsert([
            [
                'book_id' => 1,
                'title' => 'Giáo trình Tâm lý học Đại cương',
                'author' => 'Nhiều tác giả',
                'genre' => 'Giáo trình',
                'published_year' => 2022,
                'is_available' => 1,
                'cover' => 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?auto=format&fit=crop&q=80&w=600',
                'location' => 'Kệ A1',
                'is_digital' => 1,
                'resource_type' => 'Giáo trình',
                'file_format' => 'PDF',
                'file_size' => '5.2 MB',
                'download_count' => 1250,
                'total_quantity' => 4,
                'available_quantity' => 3,
            ],
            [
                'book_id' => 2,
                'title' => 'Lập trình Python cơ bản',
                'author' => 'TS. Nguyễn Mạnh Hùng',
                'genre' => 'Công nghệ thông tin',
                'published_year' => 2021,
                'is_available' => 1,
                'cover' => 'https://images.unsplash.com/photo-1532012197267-da84d127e765?auto=format&fit=crop&q=80&w=600',
                'location' => 'Kệ B2',
                'is_digital' => 1,
                'resource_type' => 'Tài liệu',
                'file_format' => 'EPUB',
                'file_size' => '3.1 MB',
                'download_count' => 840,
                'total_quantity' => 3,
                'available_quantity' => 1,
            ],
            [
                'book_id' => 3,
                'title' => 'Tạp chí Giáo dục số 452',
                'author' => 'Bộ Giáo dục và Đào tạo',
                'genre' => 'Tạp chí',
                'published_year' => 2023,
                'is_available' => 1,
                'cover' => 'https://images.unsplash.com/photo-1589829085413-56de8ae18c73?auto=format&fit=crop&q=80&w=600',
                'location' => 'Kệ C1',
                'is_digital' => 1,
                'resource_type' => 'Bài giảng',
                'file_format' => 'SLIDES',
                'file_size' => '12.5 MB',
                'download_count' => 450,
                'total_quantity' => 5,
                'available_quantity' => 5,
            ],
            [
                'book_id' => 4,
                'title' => 'Nhập môn Trí tuệ Nhân tạo',
                'author' => 'Stuart Russell',
                'genre' => 'Công nghệ thông tin',
                'published_year' => 2020,
                'is_available' => 1,
                'cover' => 'https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?auto=format&fit=crop&q=80&w=600',
                'location' => 'Kệ D4',
                'is_digital' => 1,
                'resource_type' => 'Sách nói',
                'file_format' => 'AUDIO',
                'file_size' => '45.0 MB',
                'download_count' => 3200,
                'total_quantity' => 6,
                'available_quantity' => 6,
            ],
            [
                'book_id' => 5,
                'title' => 'Vật lý Đại cương',
                'author' => 'Alonso Finn',
                'genre' => 'Giáo trình',
                'published_year' => 2018,
                'is_available' => 1,
                'cover' => 'https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&q=80&w=600',
                'location' => 'Kệ E2',
                'is_digital' => 1,
                'resource_type' => 'Tham khảo',
                'file_format' => 'PDF',
                'file_size' => '8.4 MB',
                'download_count' => 2100,
                'total_quantity' => 4,
                'available_quantity' => 4,
            ],
            [
                'book_id' => 6,
                'title' => 'Cơ sở dữ liệu ứng dụng',
                'author' => 'PGS. Trần Quốc Bảo',
                'genre' => 'Công nghệ thông tin',
                'published_year' => 2022,
                'is_available' => 1,
                'cover' => 'https://images.unsplash.com/photo-1515879218367-8466d910aaa4?auto=format&fit=crop&q=80&w=600',
                'location' => 'Kệ B3',
                'is_digital' => 1,
                'resource_type' => 'Giáo trình',
                'file_format' => 'PDF',
                'file_size' => '6.8 MB',
                'download_count' => 975,
                'total_quantity' => 5,
                'available_quantity' => 5,
            ],
            [
                'book_id' => 7,
                'title' => 'Kinh tế vi mô',
                'author' => 'N. Gregory Mankiw',
                'genre' => 'Kinh tế',
                'published_year' => 2020,
                'is_available' => 1,
                'cover' => 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&q=80&w=600',
                'location' => 'Kệ F1',
                'is_digital' => 0,
                'resource_type' => null,
                'file_format' => null,
                'file_size' => null,
                'download_count' => 0,
                'total_quantity' => 4,
                'available_quantity' => 4,
            ],
            [
                'book_id' => 8,
                'title' => 'Lịch sử Việt Nam hiện đại',
                'author' => 'GS. Phan Huy Lê',
                'genre' => 'Lịch sử',
                'published_year' => 2019,
                'is_available' => 1,
                'cover' => 'https://images.unsplash.com/photo-1461360370896-922624d12aa1?auto=format&fit=crop&q=80&w=600',
                'location' => 'Kệ G2',
                'is_digital' => 1,
                'resource_type' => 'Tài liệu',
                'file_format' => 'PDF',
                'file_size' => '7.6 MB',
                'download_count' => 630,
                'total_quantity' => 3,
                'available_quantity' => 2,
            ],
            [
                'book_id' => 9,
                'title' => 'Phương pháp nghiên cứu khoa học',
                'author' => 'TS. Lê Thị Minh Châu',
                'genre' => 'Giáo trình',
                'published_year' => 2021,
                'is_available' => 1,
                'cover' => 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?auto=format&fit=crop&q=80&w=600',
                'location' => 'Kệ A4',
                'is_digital' => 1,
                'resource_type' => 'Bài giảng',
                'file_format' => 'SLIDES',
                'file_size' => '10.2 MB',
                'download_count' => 1120,
                'total_quantity' => 6,
                'available_quantity' => 6,
            ],
            [
                'book_id' => 10,
                'title' => 'Thiết kế giao diện người dùng',
                'author' => 'Jennifer Tidwell',
                'genre' => 'Thiết kế',
                'published_year' => 2023,
                'is_available' => 1,
                'cover' => 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&q=80&w=600',
                'location' => 'Kệ H1',
                'is_digital' => 1,
                'resource_type' => 'Tham khảo',
                'file_format' => 'EPUB',
                'file_size' => '4.9 MB',
                'download_count' => 760,
                'total_quantity' => 4,
                'available_quantity' => 3,
            ],
            [
                'book_id' => 11,
                'title' => 'Mạng máy tính căn bản',
                'author' => 'Andrew S. Tanenbaum',
                'genre' => 'Công nghệ thông tin',
                'published_year' => 2020,
                'is_available' => 1,
                'cover' => 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&q=80&w=600',
                'location' => 'Kệ B5',
                'is_digital' => 1,
                'resource_type' => 'Sách nói',
                'file_format' => 'AUDIO',
                'file_size' => '38.5 MB',
                'download_count' => 540,
                'total_quantity' => 5,
                'available_quantity' => 4,
            ],
            [
                'book_id' => 12,
                'title' => 'Marketing căn bản',
                'author' => 'Philip Kotler',
                'genre' => 'Kinh tế',
                'published_year' => 2022,
                'is_available' => 1,
                'cover' => 'https://images.unsplash.com/photo-1553877522-43269d4ea984?auto=format&fit=crop&q=80&w=600',
                'location' => 'Kệ F3',
                'is_digital' => 0,
                'resource_type' => null,
                'file_format' => null,
                'file_size' => null,
                'download_count' => 0,
                'total_quantity' => 3,
                'available_quantity' => 3,
            ],
            [
                'book_id' => 13,
                'title' => 'Tiếng Anh học thuật',
                'author' => 'Michael McCarthy',
                'genre' => 'Ngoại ngữ',
                'published_year' => 2021,
                'is_available' => 1,
                'cover' => 'https://images.unsplash.com/photo-1457369804613-52c61a468e7d?auto=format&fit=crop&q=80&w=600',
                'location' => 'Kệ I2',
                'is_digital' => 1,
                'resource_type' => 'Tài liệu',
                'file_format' => 'PDF',
                'file_size' => '5.7 MB',
                'download_count' => 890,
                'total_quantity' => 7,
                'available_quantity' => 7,
            ],
            [
                'book_id' => 14,
                'title' => 'Quản trị dự án phần mềm',
                'author' => 'Kathy Schwalbe',
                'genre' => 'Công nghệ thông tin',
                'published_year' => 2024,
                'is_available' => 1,
                'cover' => 'https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?auto=format&fit=crop&q=80&w=600',
                'location' => 'Kệ D2',
                'is_digital' => 1,
                'resource_type' => 'Giáo trình',
                'file_format' => 'PDF',
                'file_size' => '9.3 MB',
                'download_count' => 410,
                'total_quantity' => 4,
                'available_quantity' => 4,
            ],
            [
                'book_id' => 15,
                'title' => 'Toán cao cấp A1',
                'author' => 'Nguyễn Đình Trí',
                'genre' => 'Giáo trình',
                'published_year' => 2018,
                'is_available' => 1,
                'cover' => 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?auto=format&fit=crop&q=80&w=600',
                'location' => 'Kệ J1',
                'is_digital' => 0,
                'resource_type' => null,
                'file_format' => null,
                'file_size' => null,
                'download_count' => 0,
                'total_quantity' => 6,
                'available_quantity' => 6,
            ],
        ], ['book_id'], [
            'title',
            'author',
            'genre',
            'published_year',
            'is_available',
            'cover',
            'location',
            'is_digital',
            'resource_type',
            'file_format',
            'file_size',
            'download_count',
            'total_quantity',
            'available_quantity',
        ]);
    }
}
